# Generated by Django 3.0.3 on 2020-07-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField()),
                ('complaint_id', models.CharField(max_length=64)),
                ('coordinates', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=512)),
                ('pothole_image', models.URLField(max_length=64)),
                ('uploaded_from', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['uploaded_time'],
            },
        ),
        migrations.CreateModel(
            name='pothole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=64)),
                ('coordinates', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=512)),
                ('status', models.CharField(default='R', max_length=2)),
                ('uploaded_timestamp', models.DateTimeField()),
                ('ongoin_timestamp', models.DateTimeField()),
                ('completed_timestamp', models.DateTimeField()),
                ('ward_no', models.IntegerField()),
                ('no_of_reporters', models.IntegerField()),
                ('feedback_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='twitter_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('complaint_id', models.CharField(max_length=64)),
                ('tweet_time', models.CharField(max_length=32)),
                ('tweet_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
