# Generated by Django 3.0.3 on 2020-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200703_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter_data',
            name='complaint_id',
        ),
        migrations.RemoveField(
            model_name='twitter_data',
            name='tweet_time',
        ),
        migrations.AddField(
            model_name='twitter_data',
            name='address',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='twitter_data',
            name='coordinates',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='twitter_data',
            name='pothole_image',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='created_at',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
