# Generated by Django 3.0.3 on 2020-07-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200703_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_data',
            name='created_at',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='tweet_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
