# Generated by Django 3.0.3 on 2020-07-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200704_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pothole',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pothole',
            name='completed_timestamp',
        ),
        migrations.RemoveField(
            model_name='pothole',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='pothole',
            name='ongoin_timestamp',
        ),
        migrations.RemoveField(
            model_name='pothole',
            name='uploaded_timestamp',
        ),
    ]
