# Generated by Django 3.0.3 on 2020-07-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200704_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='image',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
