# Generated by Django 3.0.3 on 2020-07-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_pothole_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='image',
            field=models.CharField(default='', max_length=200000),
        ),
    ]
