# Generated by Django 3.0.3 on 2020-07-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200705_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='image',
            field=models.CharField(default='', max_length=90000),
        ),
    ]
