# Generated by Django 3.0.3 on 2020-07-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200708_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pothole_image',
            field=models.ImageField(blank='True', upload_to='pothole_pictures'),
        ),
    ]
