# Generated by Django 3.0.3 on 2020-07-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200708_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsapp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank='True', default='', max_length=64)),
                ('number', models.CharField(blank='True', default='', max_length=256)),
                ('name', models.CharField(blank='True', default='', max_length=128)),
            ],
        ),
    ]
