# Generated by Django 3.0.3 on 2020-07-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_whatsapp_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
