# Generated by Django 3.0.3 on 2020-07-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20200709_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pothole',
            old_name='ongoin_timestamp',
            new_name='ongoing_timestamp',
        ),
        migrations.AlterField(
            model_name='pothole',
            name='no_of_reporters',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='ward_no',
            field=models.IntegerField(default=108),
        ),
    ]
