# Generated by Django 3.0.3 on 2020-07-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20200725_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='complaint_id',
            field=models.CharField(blank='True', default='', max_length=3000),
        ),
    ]
