# Generated by Django 3.0.3 on 2020-07-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20200731_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='feedback_flag',
            field=models.CharField(default='Registered', max_length=25),
        ),
    ]
