# Generated by Django 3.0.3 on 2020-07-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20200731_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='complaint_id_duplicate',
            field=models.CharField(blank='True', default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='complaint_id',
            field=models.CharField(blank='True', default='', max_length=40),
        ),
    ]
